# Generated by Django 6.0.7 on 2026-07-30 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('orientation', models.CharField(blank=True, choices=[('SUPPORTIVE', 'Supportive'), ('NEUTRAL', 'Neutral'), ('OPPOSED', 'Opposed'), ('UNKNOWN', 'Unknown')], max_length=20, null=True)),
                ('niches', models.JSONField(blank=True, default=list)),
                ('minimum_followers', models.BigIntegerField(default=0)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('language_match', models.BooleanField(default=False)),
                ('orientation_match', models.BooleanField(default=False)),
                ('niche_match', models.BooleanField(default=False)),
                ('keyword_match', models.BooleanField(default=False)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('RECOMMEND', 'Recommend'), ('MAYBE', 'Maybe'), ('REJECT', 'Reject')], default='MAYBE', max_length=20)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='influencers.influencer')),
                ('search_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='classification.searchcriteria')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['influencer', 'search_criteria'], name='classificat_influen_954052_idx'), models.Index(fields=['status'], name='classificat_status_6e856c_idx')],
            },
        ),
    ]
