# Generated by Django 6.0.7 on 2026-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='ai_model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='processing_time_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='classification',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
