# Generated by Django 6.0.7 on 2026-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_uploads', models.IntegerField(default=0)),
                ('total_influencers', models.IntegerField(default=0)),
                ('relevant_influencers', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top_platform', models.CharField(blank=True, max_length=50)),
                ('top_language', models.CharField(blank=True, max_length=100)),
                ('snapshot_date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
