# Generated by Django 6.0.7 on 2026-07-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0002_upload_processing_status_alter_upload_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('followers', models.BigIntegerField(db_index=True, default=0)),
                ('following', models.BigIntegerField(default=0)),
                ('total_posts', models.BigIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='uploads.upload')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['handle'], name='influencers_handle_c9cb3f_idx'), models.Index(fields=['platform'], name='influencers_platfor_4e69c4_idx'), models.Index(fields=['language'], name='influencers_languag_d4ca9b_idx'), models.Index(fields=['followers'], name='influencers_followe_452660_idx')],
                'constraints': [models.UniqueConstraint(fields=('handle', 'platform'), name='unique_influencer_handle_platform'), models.CheckConstraint(condition=models.Q(('followers__gte', 0)), name='followers_non_negative')],
            },
        ),
    ]
