# Generated by Django 6.0.7 on 2026-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='extracted_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='influencer',
            name='extracted_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='influencer',
            name='language_confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='influencer',
            name='language_detected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='nlp_matched_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='influencer',
            name='nlp_matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='influencer',
            name='nlp_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='rule_based_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
