# Generated by Django 6.0.7 on 2026-07-30 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_influencer_extracted_entities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='source',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded File'), ('MOCK', 'Mock Provider'), ('INSTAGRAM', 'Instagram API'), ('YOUTUBE', 'YouTube API'), ('TWITTER', 'Twitter API'), ('LINKEDIN', 'LinkedIn API')], default='UPLOADED', max_length=50),
        ),
        migrations.AddField(
            model_name='influencer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to=settings.AUTH_USER_MODEL),
        ),
    ]
