# Generated by Django 6.0.7 on 2026-07-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencer_discovered_at_influencer_external_id_and_more'),
        ('uploads', '0003_upload_processing_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='uploads.upload'),
        ),
    ]
