# Generated by Django 6.0.7 on 2026-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_processing_status_alter_upload_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='processing_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Processing statistics: total_rows, imported, duplicates, invalid, processing_time_seconds'),
        ),
    ]
